runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /
  static_files: www/index.html
  upload: www/index.html

- url: /
  static_dir: www

- url: /css
  static_dir: www/css
  upload: www/css

- url: /js
  static_dir: www/js
  upload: www/js